[2025-01-09T00:01:35.362+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-09T00:01:35.373+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-09T00:01:35.373+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-01-09T00:01:35.386+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-01-09T00:01:35.386+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-01-09T00:01:35.418+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.stocks_run> on 2025-01-08 00:00:00+00:00
[2025-01-09T00:01:35.423+0000] {standard_task_runner.py:55} INFO - Started process 1668 to run task
[2025-01-09T00:01:35.425+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.stocks_run', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '648', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpu43ptjcp']
[2025-01-09T00:01:35.426+0000] {standard_task_runner.py:83} INFO - Job 648: Subtask dbt_transformation.stocks.stocks_run
[2025-01-09T00:01:35.577+0000] {task_command.py:388} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run scheduled__2025-01-08T00:00:00+00:00 [running]> on host 65047f1edb18
[2025-01-09T00:01:35.698+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PolygonAPI_to_BigQuery
AIRFLOW_CTX_TASK_ID=dbt_transformation.stocks.stocks_run
AIRFLOW_CTX_EXECUTION_DATE=2025-01-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-08T00:00:00+00:00
[2025-01-09T00:01:35.708+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:35,707[0m] {[34mlocal.py:[0m146} INFO[0m - [33m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmp96e7pmbg from /opt/***/dbt/dbt_stock_project[0m
[2025-01-09T00:01:36.216+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:36,216[0m] {[34mconfig.py:[0m139} INFO[0m - [33m(astronomer-cosmos)[0m - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml[0m
[2025-01-09T00:01:36.216+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:36,216[0m] {[34mlocal.py:[0m176} INFO[0m - [33m(astronomer-cosmos)[0m - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
From /tmp/tmp96e7pmbg/dbt_project[0m
[2025-01-09T00:01:36.218+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:36,217[0m] {[34mlocal.py:[0m177} INFO[0m - [33m(astronomer-cosmos)[0m - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])[0m
[2025-01-09T00:01:36.218+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:36,218[0m] {[34msubprocess.py:[0m60} INFO[0m - [33m(astronomer-cosmos)[0m - Tmp dir root location: 
 /tmp[0m
[2025-01-09T00:01:36.218+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:36,218[0m] {[34msubprocess.py:[0m73} INFO[0m - [33m(astronomer-cosmos)[0m - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev'][0m
[2025-01-09T00:01:36.227+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:36,227[0m] {[34msubprocess.py:[0m84} INFO[0m - [33m(astronomer-cosmos)[0m - Command output:[0m
[2025-01-09T00:01:39.296+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:39,296[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m00:01:39  Running with dbt=1.5.11[0m
[2025-01-09T00:01:40.668+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,668[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m00:01:40  Encountered an error:[0m
[2025-01-09T00:01:40.668+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,668[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - invalid syntax (column.py, line 230)[0m
[2025-01-09T00:01:40.669+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,669[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m00:01:40  Traceback (most recent call last):[0m
[2025-01-09T00:01:40.670+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,670[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper[0m
[2025-01-09T00:01:40.670+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,670[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     result, success = func(*args, **kwargs)[0m
[2025-01-09T00:01:40.671+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,671[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper[0m
[2025-01-09T00:01:40.671+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,671[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return func(*args, **kwargs)[0m
[2025-01-09T00:01:40.672+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,672[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper[0m
[2025-01-09T00:01:40.672+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,672[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)[0m
[2025-01-09T00:01:40.673+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,672[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile[0m
[2025-01-09T00:01:40.673+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,673[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile_renderer, profile_name, profile_name_override, target_override, threads_override[0m
[2025-01-09T00:01:40.674+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,673[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render[0m
[2025-01-09T00:01:40.674+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,674[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     threads_override=threads_override,[0m
[2025-01-09T00:01:40.675+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,674[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles[0m
[2025-01-09T00:01:40.675+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,675[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     threads_override=threads_override,[0m
[2025-01-09T00:01:40.676+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,675[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info[0m
[2025-01-09T00:01:40.676+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,676[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile_data, profile_name, target_name[0m
[2025-01-09T00:01:40.677+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,677[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile[0m
[2025-01-09T00:01:40.677+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,677[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     cls = load_plugin(typename)[0m
[2025-01-09T00:01:40.678+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,678[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin[0m
[2025-01-09T00:01:40.678+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,678[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return FACTORY.load_plugin(name)[0m
[2025-01-09T00:01:40.679+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,679[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin[0m
[2025-01-09T00:01:40.679+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,679[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     mod: Any = import_module("." + name, "dbt.adapters")[0m
[2025-01-09T00:01:40.680+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,680[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module[0m
[2025-01-09T00:01:40.680+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,680[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return _bootstrap._gcd_import(name[level:], package, level)[0m
[2025-01-09T00:01:40.681+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,681[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import[0m
[2025-01-09T00:01:40.681+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,681[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load[0m
[2025-01-09T00:01:40.682+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,682[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked[0m
[2025-01-09T00:01:40.683+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,683[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked[0m
[2025-01-09T00:01:40.683+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,683[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module[0m
[2025-01-09T00:01:40.684+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,684[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed[0m
[2025-01-09T00:01:40.684+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,684[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>[0m
[2025-01-09T00:01:40.685+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,685[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     from dbt.adapters.bigquery.column import BigQueryColumn  # noqa[0m
[2025-01-09T00:01:40.685+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,685[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230[0m
[2025-01-09T00:01:40.686+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,686[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):[0m
[2025-01-09T00:01:40.686+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,686[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -                                          ^[0m
[2025-01-09T00:01:40.687+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,687[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - SyntaxError: invalid syntax[0m
[2025-01-09T00:01:40.687+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:40,687[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m
[2025-01-09T00:01:41.682+0000] {log.py:232} WARNING - [[34m2025-01-09 00:01:41,681[0m] {[34msubprocess.py:[0m98} INFO[0m - [33m(astronomer-cosmos)[0m - Command exited with return code 2[0m
[2025-01-09T00:01:41.695+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 282, in execute
    result = self.build_and_run_cmd(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 194, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 185, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 79, in exception_handling
    *result.full_output,
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m00:01:39  Running with dbt=1.5.11', '\x1b[0m00:01:40  Encountered an error:', 'invalid syntax (column.py, line 230)', '\x1b[0m00:01:40  Traceback (most recent call last):', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper', '    result, success = func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper', '    return func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper', '    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile', '    profile_renderer, profile_name, profile_name_override, target_override, threads_override', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info', '    profile_data, profile_name, target_name', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile', '    cls = load_plugin(typename)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin', '    return FACTORY.load_plugin(name)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin', '    mod: Any = import_module("." + name, "dbt.adapters")', '  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module', '    return _bootstrap._gcd_import(name[level:], package, level)', '  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import', '  File "<frozen importlib._bootstrap>", line 983, in _find_and_load', '  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked', '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked', '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>', '    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230', '    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):', '                                         ^', 'SyntaxError: invalid syntax', '')
[2025-01-09T00:01:41.699+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.stocks_run, execution_date=20250108T000000, start_date=20250109T000135, end_date=20250109T000141
[2025-01-09T00:01:41.760+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 648 for task dbt_transformation.stocks.stocks_run (('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m00:01:39  Running with dbt=1.5.11', '\x1b[0m00:01:40  Encountered an error:', 'invalid syntax (column.py, line 230)', '\x1b[0m00:01:40  Traceback (most recent call last):', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper', '    result, success = func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper', '    return func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper', '    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile', '    profile_renderer, profile_name, profile_name_override, target_override, threads_override', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info', '    profile_data, profile_name, target_name', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile', '    cls = load_plugin(typename)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin', '    return FACTORY.load_plugin(name)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin', '    mod: Any = import_module("." + name, "dbt.adapters")', '  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module', '    return _bootstrap._gcd_import(name[level:], package, level)', '  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import', '  File "<frozen importlib._bootstrap>", line 983, in _find_and_load', '  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked', '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked', '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>', '    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230', '    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):', '                                         ^', 'SyntaxError: invalid syntax', ''); 1668)
[2025-01-09T00:01:41.780+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-01-09T00:01:41.847+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
