[2025-01-08T23:51:21.693+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:50:01.523970+00:00 [queued]>
[2025-01-08T23:51:21.705+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:50:01.523970+00:00 [queued]>
[2025-01-08T23:51:21.705+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-01-08T23:51:21.706+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-01-08T23:51:21.706+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-01-08T23:51:21.722+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.stocks_run> on 2025-01-08 23:50:01.523970+00:00
[2025-01-08T23:51:21.726+0000] {standard_task_runner.py:55} INFO - Started process 641 to run task
[2025-01-08T23:51:21.729+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.stocks_run', 'manual__2025-01-08T23:50:01.523970+00:00', '--job-id', '641', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmp5jfebks1']
[2025-01-08T23:51:21.730+0000] {standard_task_runner.py:83} INFO - Job 641: Subtask dbt_transformation.stocks.stocks_run
[2025-01-08T23:51:21.793+0000] {task_command.py:388} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:50:01.523970+00:00 [running]> on host 65047f1edb18
[2025-01-08T23:51:21.868+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PolygonAPI_to_BigQuery
AIRFLOW_CTX_TASK_ID=dbt_transformation.stocks.stocks_run
AIRFLOW_CTX_EXECUTION_DATE=2025-01-08T23:50:01.523970+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-08T23:50:01.523970+00:00
[2025-01-08T23:51:21.870+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:21,870[0m] {[34mlocal.py:[0m146} INFO[0m - [33m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmp6t222gmr from /opt/***/dbt/dbt_stock_project[0m
[2025-01-08T23:51:22.431+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:22,431[0m] {[34mconfig.py:[0m139} INFO[0m - [33m(astronomer-cosmos)[0m - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml[0m
[2025-01-08T23:51:22.432+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:22,431[0m] {[34mlocal.py:[0m176} INFO[0m - [33m(astronomer-cosmos)[0m - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
From /tmp/tmp6t222gmr/dbt_project[0m
[2025-01-08T23:51:22.433+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:22,432[0m] {[34mlocal.py:[0m177} INFO[0m - [33m(astronomer-cosmos)[0m - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])[0m
[2025-01-08T23:51:22.434+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:22,434[0m] {[34msubprocess.py:[0m60} INFO[0m - [33m(astronomer-cosmos)[0m - Tmp dir root location: 
 /tmp[0m
[2025-01-08T23:51:22.434+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:22,434[0m] {[34msubprocess.py:[0m73} INFO[0m - [33m(astronomer-cosmos)[0m - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev'][0m
[2025-01-08T23:51:22.445+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:22,445[0m] {[34msubprocess.py:[0m84} INFO[0m - [33m(astronomer-cosmos)[0m - Command output:[0m
[2025-01-08T23:51:25.443+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:25,443[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m23:51:25  Running with dbt=1.5.11[0m
[2025-01-08T23:51:26.658+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,658[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m23:51:26  Encountered an error:[0m
[2025-01-08T23:51:26.658+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,658[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - invalid syntax (column.py, line 230)[0m
[2025-01-08T23:51:26.661+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,661[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m23:51:26  Traceback (most recent call last):[0m
[2025-01-08T23:51:26.661+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,661[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper[0m
[2025-01-08T23:51:26.662+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,662[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     result, success = func(*args, **kwargs)[0m
[2025-01-08T23:51:26.662+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,662[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper[0m
[2025-01-08T23:51:26.662+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,662[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return func(*args, **kwargs)[0m
[2025-01-08T23:51:26.663+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,663[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper[0m
[2025-01-08T23:51:26.663+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,663[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)[0m
[2025-01-08T23:51:26.663+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,663[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile[0m
[2025-01-08T23:51:26.664+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,664[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile_renderer, profile_name, profile_name_override, target_override, threads_override[0m
[2025-01-08T23:51:26.664+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,664[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render[0m
[2025-01-08T23:51:26.664+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,664[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     threads_override=threads_override,[0m
[2025-01-08T23:51:26.665+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,665[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles[0m
[2025-01-08T23:51:26.665+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,665[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     threads_override=threads_override,[0m
[2025-01-08T23:51:26.666+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,666[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info[0m
[2025-01-08T23:51:26.666+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,666[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile_data, profile_name, target_name[0m
[2025-01-08T23:51:26.667+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,667[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile[0m
[2025-01-08T23:51:26.667+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,667[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     cls = load_plugin(typename)[0m
[2025-01-08T23:51:26.668+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,668[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin[0m
[2025-01-08T23:51:26.668+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,668[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return FACTORY.load_plugin(name)[0m
[2025-01-08T23:51:26.669+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,669[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin[0m
[2025-01-08T23:51:26.669+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,669[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     mod: Any = import_module("." + name, "dbt.adapters")[0m
[2025-01-08T23:51:26.669+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,669[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module[0m
[2025-01-08T23:51:26.670+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,670[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return _bootstrap._gcd_import(name[level:], package, level)[0m
[2025-01-08T23:51:26.670+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,670[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import[0m
[2025-01-08T23:51:26.670+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,670[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load[0m
[2025-01-08T23:51:26.671+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,671[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked[0m
[2025-01-08T23:51:26.671+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,671[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked[0m
[2025-01-08T23:51:26.672+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,672[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module[0m
[2025-01-08T23:51:26.672+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,672[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed[0m
[2025-01-08T23:51:26.673+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,673[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>[0m
[2025-01-08T23:51:26.673+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,673[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     from dbt.adapters.bigquery.column import BigQueryColumn  # noqa[0m
[2025-01-08T23:51:26.673+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,673[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230[0m
[2025-01-08T23:51:26.674+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,674[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):[0m
[2025-01-08T23:51:26.674+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,674[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -                                          ^[0m
[2025-01-08T23:51:26.675+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,675[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - SyntaxError: invalid syntax[0m
[2025-01-08T23:51:26.675+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:26,675[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m
[2025-01-08T23:51:27.658+0000] {log.py:232} WARNING - [[34m2025-01-08 23:51:27,658[0m] {[34msubprocess.py:[0m98} INFO[0m - [33m(astronomer-cosmos)[0m - Command exited with return code 2[0m
[2025-01-08T23:51:27.671+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 282, in execute
    result = self.build_and_run_cmd(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 194, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 185, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 79, in exception_handling
    *result.full_output,
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m23:51:25  Running with dbt=1.5.11', '\x1b[0m23:51:26  Encountered an error:', 'invalid syntax (column.py, line 230)', '\x1b[0m23:51:26  Traceback (most recent call last):', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper', '    result, success = func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper', '    return func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper', '    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile', '    profile_renderer, profile_name, profile_name_override, target_override, threads_override', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info', '    profile_data, profile_name, target_name', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile', '    cls = load_plugin(typename)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin', '    return FACTORY.load_plugin(name)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin', '    mod: Any = import_module("." + name, "dbt.adapters")', '  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module', '    return _bootstrap._gcd_import(name[level:], package, level)', '  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import', '  File "<frozen importlib._bootstrap>", line 983, in _find_and_load', '  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked', '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked', '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>', '    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230', '    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):', '                                         ^', 'SyntaxError: invalid syntax', '')
[2025-01-08T23:51:27.676+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.stocks_run, execution_date=20250108T235001, start_date=20250108T235121, end_date=20250108T235127
[2025-01-08T23:51:27.694+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 641 for task dbt_transformation.stocks.stocks_run (('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m23:51:25  Running with dbt=1.5.11', '\x1b[0m23:51:26  Encountered an error:', 'invalid syntax (column.py, line 230)', '\x1b[0m23:51:26  Traceback (most recent call last):', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper', '    result, success = func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper', '    return func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper', '    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile', '    profile_renderer, profile_name, profile_name_override, target_override, threads_override', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info', '    profile_data, profile_name, target_name', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile', '    cls = load_plugin(typename)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin', '    return FACTORY.load_plugin(name)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin', '    mod: Any = import_module("." + name, "dbt.adapters")', '  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module', '    return _bootstrap._gcd_import(name[level:], package, level)', '  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import', '  File "<frozen importlib._bootstrap>", line 983, in _find_and_load', '  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked', '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked', '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>', '    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230', '    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):', '                                         ^', 'SyntaxError: invalid syntax', ''); 641)
[2025-01-08T23:51:27.720+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-01-08T23:51:27.748+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
