[2025-01-17T17:58:27.483+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_5 scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T17:58:27.555+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_5 scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T17:58:27.556+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-17T17:58:27.618+0000] {taskinstance.py:1382} INFO - Executing <Task(AirbyteTriggerSyncOperator): sync_data_connection_5> on 2025-01-16 00:00:00+00:00
[2025-01-17T17:58:27.628+0000] {standard_task_runner.py:57} INFO - Started process 12270 to run task
[2025-01-17T17:58:27.644+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'sync_data_connection_5', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpm4i9zyax']
[2025-01-17T17:58:27.649+0000] {standard_task_runner.py:85} INFO - Job 381: Subtask sync_data_connection_5
[2025-01-17T17:58:27.768+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_5 scheduled__2025-01-16T00:00:00+00:00 [running]> on host a7a323ab681c
[2025-01-17T17:58:33.240+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='sync_data_connection_5' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-01-17T17:58:33.260+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2025-01-17T17:58:34.250+0000] {airbyte.py:95} INFO - Job 348 was submitted to Airbyte Server
[2025-01-17T17:58:34.251+0000] {airbyte.py:97} INFO - Waiting for job 348 to complete
[2025-01-17T17:58:37.292+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2025-01-17T17:58:40.347+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2025-01-17T17:58:43.419+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2025-01-17T17:58:46.485+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2025-01-17T17:58:49.539+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2025-01-17T18:14:47.611+0000] {http.py:221} WARNING - ('Connection aborted.', OSError(113, 'No route to host')) Tenacity will retry to execute the operation
