[2025-01-13T00:18:34.113+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run scheduled__2025-01-12T00:00:00+00:00 [queued]>
[2025-01-13T00:18:34.129+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run scheduled__2025-01-12T00:00:00+00:00 [queued]>
[2025-01-13T00:18:34.129+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T00:18:34.141+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-12 00:00:00+00:00
[2025-01-13T00:18:34.146+0000] {standard_task_runner.py:57} INFO - Started process 4682 to run task
[2025-01-13T00:18:34.149+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'scheduled__2025-01-12T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmp5uxonqxd']
[2025-01-13T00:18:34.153+0000] {standard_task_runner.py:85} INFO - Job 269: Subtask dbt_transformation.stocks.run
[2025-01-13T00:18:34.194+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run scheduled__2025-01-12T00:00:00+00:00 [running]> on host 8e83bd89ed82
[2025-01-13T00:18:35.078+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-12T00:00:00+00:00'
[2025-01-13T00:18:37.657+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T00:18:37.658+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpk4sf6xq6 from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T00:18:37.664+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /opt/airflow/dbt/dbt_stock_project/target/partial_parse.msgpack
[2025-01-13T00:18:37.693+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T00:18:37.694+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmpk4sf6xq6', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpk4sf6xq6
[2025-01-13T00:18:37.746+0000] {eventmgr.py:60} DEBUG - [0m00:18:37.732375 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f416cfb4160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4167ef58b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4167ef5670>]}
[2025-01-13T00:18:37.747+0000] {logging_mixin.py:151} INFO - 00:18:37  Running with dbt=1.5.11
[2025-01-13T00:18:37.747+0000] {eventmgr.py:62} INFO - [0m00:18:37  Running with dbt=1.5.11
[2025-01-13T00:18:37.748+0000] {eventmgr.py:62} INFO - 

============================== 00:18:37.747328 | 32a0a788-2b78-4163-94aa-6cd6113eff0c ==============================
[0m00:18:37.747328 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T00:18:37.749+0000] {eventmgr.py:60} DEBUG - [0m00:18:37.749630 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/***/dbt/profiles', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/tmp/tmpk4sf6xq6/logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T00:18:38.985+0000] {eventmgr.py:60} DEBUG - [0m00:18:38.985401 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '32a0a788-2b78-4163-94aa-6cd6113eff0c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4167ef5070>]}
[2025-01-13T00:18:39.029+0000] {eventmgr.py:60} DEBUG - [0m00:18:39.028964 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '32a0a788-2b78-4163-94aa-6cd6113eff0c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f41660c56a0>]}
[2025-01-13T00:18:39.031+0000] {logging_mixin.py:151} INFO - 00:18:39  Registered adapter: bigquery=1.5.9
[2025-01-13T00:18:39.031+0000] {eventmgr.py:62} INFO - [0m00:18:39  Registered adapter: bigquery=1.5.9
[2025-01-13T00:18:39.032+0000] {eventmgr.py:62} INFO - [0m00:18:39.030825 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T00:18:39.059+0000] {eventmgr.py:60} DEBUG - [0m00:18:39.059472 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T00:18:39.213+0000] {logging_mixin.py:151} INFO - 00:18:39  Unable to do partial parsing because of a version mismatch
[2025-01-13T00:18:39.213+0000] {eventmgr.py:62} INFO - [0m00:18:39  Unable to do partial parsing because of a version mismatch
[2025-01-13T00:18:39.215+0000] {eventmgr.py:62} INFO - [0m00:18:39.213303 [info ] [MainThread]: Unable to do partial parsing because of a version mismatch
[2025-01-13T00:18:39.216+0000] {eventmgr.py:60} DEBUG - [0m00:18:39.216052 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '32a0a788-2b78-4163-94aa-6cd6113eff0c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4165e2a1c0>]}
[2025-01-13T00:18:41.055+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.055537 [debug] [MainThread]: 1699: static parser successfully parsed stocks.sql
[2025-01-13T00:18:41.313+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.312818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '32a0a788-2b78-4163-94aa-6cd6113eff0c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4165e54df0>]}
[2025-01-13T00:18:41.325+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.325359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '32a0a788-2b78-4163-94aa-6cd6113eff0c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f41660f47c0>]}
[2025-01-13T00:18:41.327+0000] {logging_mixin.py:151} INFO - 00:18:41  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:18:41.326+0000] {eventmgr.py:62} INFO - [0m00:18:41  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:18:41.328+0000] {eventmgr.py:62} INFO - [0m00:18:41.326617 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:18:41.329+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.328784 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '32a0a788-2b78-4163-94aa-6cd6113eff0c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4165e6db50>]}
[2025-01-13T00:18:41.331+0000] {logging_mixin.py:151} INFO - 00:18:41
[2025-01-13T00:18:41.331+0000] {eventmgr.py:62} INFO - [0m00:18:41  
[2025-01-13T00:18:41.332+0000] {eventmgr.py:62} INFO - [0m00:18:41.330972 [info ] [MainThread]: 
[2025-01-13T00:18:41.334+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.333836 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T00:18:41.336+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.336490 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T00:18:41.338+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.337707 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T00:18:41.340+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.340489 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json''
[2025-01-13T00:18:41.343+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.343153 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T00:18:41.344+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.344219 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T00:18:41.345+0000] {logging_mixin.py:151} INFO - 00:18:41
[2025-01-13T00:18:41.345+0000] {eventmgr.py:62} INFO - [0m00:18:41  
[2025-01-13T00:18:41.346+0000] {eventmgr.py:62} INFO - [0m00:18:41.345195 [info ] [MainThread]: 
[2025-01-13T00:18:41.347+0000] {logging_mixin.py:151} INFO - 00:18:41  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:18:41.347+0000] {eventmgr.py:62} INFO - [0m00:18:41  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:18:41.349+0000] {eventmgr.py:62} INFO - [0m00:18:41.347485 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:18:41.350+0000] {logging_mixin.py:151} INFO - 00:18:41  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:18:41.350+0000] {eventmgr.py:66} ERROR - [0m00:18:41  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:18:41.351+0000] {eventmgr.py:66} ERROR - [0m00:18:41.349839 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:18:41.352+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.352533 [debug] [MainThread]: Command `cli run` failed at 00:18:41.352366 after 3.65 seconds
[2025-01-13T00:18:41.354+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.353652 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f416cfb4160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4165e41610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4165e5d640>]}
[2025-01-13T00:18:41.355+0000] {eventmgr.py:60} DEBUG - [0m00:18:41.354993 [debug] [MainThread]: Flushing usage events
[2025-01-13T00:18:42.632+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T00:18:42.633+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T00:18:42.634+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T00:18:42.634+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T00:18:42.635+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T00:18:42.661+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T00:18:42.693+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:18:42.698+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250112T000000, start_date=20250113T001834, end_date=20250113T001842
[2025-01-13T00:18:42.713+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 269 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'; 4682)
[2025-01-13T00:18:42.746+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T00:18:42.780+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
